# Generated by Django 6.0.2 on 2026-06-30 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisExpert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1 étoile(s)'), (2, '2 étoile(s)'), (3, '3 étoile(s)'), (4, '4 étoile(s)'), (5, '5 étoile(s)')])),
                ('commentaire', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_deposes', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(limit_choices_to={'profil__role': 'expert'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis expert',
                'verbose_name_plural': 'Avis experts',
                'ordering': ['-created_at'],
                'unique_together': {('expert', 'auteur')},
            },
        ),
    ]
