# Generated by Django 6.0.2 on 2026-03-01 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impot', models.CharField(choices=[('tva', 'TVA — Taxe sur la Valeur Ajoutée'), ('is', 'IS — Impôt sur les Sociétés'), ('cnps', 'CNPS — Caisse Nationale de Prévoyance Sociale'), ('bnc', 'BNC — Bénéfices Non Commerciaux'), ('bic', 'BIC — Bénéfices Industriels et Commerciaux')], max_length=10)),
                ('periode', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=15)),
                ('annee', models.PositiveIntegerField()),
                ('mois', models.PositiveIntegerField(blank=True, help_text='1-12 pour mensuel', null=True)),
                ('trimestre', models.PositiveIntegerField(blank=True, help_text='1-4 pour trimestriel', null=True)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('benefice_net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taux_applique', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_impot', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('soumise', 'Soumise'), ('validee', 'Validée'), ('en_retard', 'En retard')], default='en_attente', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Déclaration fiscale',
                'verbose_name_plural': 'Déclarations fiscales',
                'ordering': ['-annee', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_impot', models.CharField(choices=[('tva', 'TVA — Taxe sur la Valeur Ajoutée'), ('is', 'IS — Impôt sur les Sociétés'), ('cnps', 'CNPS — Caisse Nationale de Prévoyance Sociale'), ('bnc', 'BNC — Bénéfices Non Commerciaux'), ('bic', 'BIC — Bénéfices Industriels et Commerciaux')], max_length=10)),
                ('date_limite', models.DateField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('fait', 'Fait'), ('en_retard', 'En retard')], default='a_faire', max_length=15)),
                ('rappel_email', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Échéance fiscale',
                'verbose_name_plural': 'Échéances fiscales',
                'ordering': ['date_limite'],
            },
        ),
    ]
