# Generated by Django 6.0.2 on 2026-04-21 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='declaration',
            name='date_soumission_expert',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='declaration',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_a_reviser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='declaration',
            name='soumise_a_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('soumise', 'Soumise'), ('en_revision', 'En révision'), ('validee', 'Validée'), ('en_retard', 'En retard')], default='en_attente', max_length=15),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='type_impot',
            field=models.CharField(choices=[('tva', 'TVA — Taxe sur la Valeur Ajoutée'), ('is', 'IS — Impôt sur les Sociétés'), ('cnps', 'CNPS — Caisse Nationale de Prévoyance Sociale'), ('bnc', 'BNC — Bénéfices Non Commerciaux'), ('bic', 'BIC — Bénéfices Industriels et Commerciaux'), ('patente', 'Patente — Taxe professionnelle'), ('tse', "TSE — Taxe Spéciale sur l'Équipement"), ('imf', 'IMF — Impôt Minimum Forfaitaire')], max_length=10),
        ),
        migrations.AlterField(
            model_name='echeance',
            name='type_impot',
            field=models.CharField(choices=[('tva', 'TVA — Taxe sur la Valeur Ajoutée'), ('is', 'IS — Impôt sur les Sociétés'), ('cnps', 'CNPS — Caisse Nationale de Prévoyance Sociale'), ('bnc', 'BNC — Bénéfices Non Commerciaux'), ('bic', 'BIC — Bénéfices Industriels et Commerciaux'), ('patente', 'Patente — Taxe professionnelle'), ('tse', "TSE — Taxe Spéciale sur l'Équipement"), ('imf', 'IMF — Impôt Minimum Forfaitaire')], max_length=10),
        ),
        migrations.CreateModel(
            name='CommentaireDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('est_expert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='fiscalite.declaration')),
            ],
            options={
                'verbose_name': 'Commentaire de déclaration',
                'verbose_name_plural': 'Commentaires de déclarations',
                'ordering': ['created_at'],
            },
        ),
    ]
