# Generated by Django 6.0.2 on 2026-06-26 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_chatbot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation chatbot',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='MessageChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediteur', models.CharField(choices=[('user', 'Utilisateur'), ('bot', 'Chatbot')], max_length=4)),
                ('contenu', models.TextField()),
                ('intention', models.CharField(blank=True, max_length=50)),
                ('escalade', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversationchatbot')),
            ],
            options={
                'verbose_name': 'Message chatbot',
                'ordering': ['cree_le'],
            },
        ),
    ]
