# Generated by Django 6.0.2 on 2026-03-01 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commercant', 'Commerçant'), ('prestataire', 'Prestataire'), ('fonctionnaire', 'Fonctionnaire'), ('expert', 'Expert'), ('admin', 'Administrateur'), ('institution', 'Institution')], default='commercant', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
