# Generated by Django 6.0.2 on 2026-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profil',
            name='specialite',
            field=models.CharField(blank=True, choices=[('droit_commercial', 'Droit Commercial'), ('droit_travail', 'Droit du Travail'), ('droit_fiscal', 'Droit Fiscal'), ('comptabilite', 'Comptabilité & Finance'), ('droit_immobilier', 'Droit Immobilier'), ('droit_penal', 'Droit Pénal des Affaires'), ('droit_civil', 'Droit Civil'), ('audit', 'Audit & Contrôle')], help_text='Spécialité principale (experts uniquement)', max_length=30),
        ),
        migrations.AddField(
            model_name='profil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('commercant', 'Commerçant'), ('prestataire', 'Prestataire de services'), ('fonctionnaire', 'Fonctionnaire'), ('expert', 'Expert juridique / comptable'), ('institution', 'Institution / ONG'), ('admin', 'Administrateur')], default='commercant', max_length=20),
        ),
    ]
