# Generated by Django 6.0.2 on 2026-04-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profil_avatar_profil_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('commercant', 'Commerçant'), ('prestataire', 'Prestataire de services'), ('expert', 'Expert juridique / comptable'), ('institution', 'Institution / ONG'), ('admin', 'Administrateur')], default='commercant', max_length=20),
        ),
    ]
