# Generated by Django 6.0.2 on 2026-03-01 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('prestation', 'Contrat de prestation de service'), ('vente', 'Contrat de vente'), ('bail', 'Contrat de bail commercial'), ('travail', 'Contrat de travail'), ('partenariat', 'Contrat de partenariat'), ('collaboration', 'Convention de collaboration'), ('confidentialite', 'Accord de confidentialité (NDA)')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contenu', models.TextField(help_text='Template avec variables {{nom_client}}, {{date}}, etc.')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Modèle de contrat',
                'verbose_name_plural': 'Modèles de contrats',
                'ordering': ['type_contrat', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('prestation', 'Contrat de prestation de service'), ('vente', 'Contrat de vente'), ('bail', 'Contrat de bail commercial'), ('travail', 'Contrat de travail'), ('partenariat', 'Contrat de partenariat'), ('collaboration', 'Convention de collaboration'), ('confidentialite', 'Accord de confidentialité (NDA)')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('finalise', 'Finalisé'), ('signe', 'Signé'), ('archive', 'Archivé')], default='brouillon', max_length=20)),
                ('nom_client', models.CharField(max_length=200, verbose_name='Nom du client / Preneur')),
                ('email_client', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('adresse_client', models.TextField(blank=True)),
                ('nom_prestataire', models.CharField(max_length=200, verbose_name='Nom du prestataire / Bailleur')),
                ('email_prestataire', models.EmailField(blank=True, max_length=254)),
                ('telephone_prestataire', models.CharField(blank=True, max_length=20)),
                ('adresse_prestataire', models.TextField(blank=True)),
                ('objet', models.TextField(verbose_name='Objet du contrat')),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('lieu_signature', models.CharField(blank=True, max_length=200)),
                ('clauses_speciales', models.TextField(blank=True, verbose_name='Clauses particulières')),
                ('contenu_final', models.TextField(blank=True, verbose_name='Contenu final du contrat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_expert', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contrats.modelecontrat')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-created_at'],
            },
        ),
    ]
