# Generated by Django 6.0.2 on 2026-03-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='ca_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires TTC"),
        ),
        migrations.AddField(
            model_name='contrat',
            name='charges_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Charges / Achats HT (FCFA)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='chiffre_affaires_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name="Chiffre d'affaires HT (FCFA)"),
        ),
        migrations.AddField(
            model_name='contrat',
            name='tva_collectee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TVA collectée (18%)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='tva_deductible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TVA déductible (18% sur achats)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='tva_nette',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TVA nette à reverser'),
        ),
    ]
