# Generated by Django 6.0.2 on 2026-03-15 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_add_fiscal_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='ca_ttc',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='charges_ht',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='chiffre_affaires_ht',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='tva_collectee',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='tva_deductible',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='tva_nette',
        ),
    ]
