# Generated by Django 6.0.2 on 2026-03-01 06:28

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('declaration', 'Déclaration fiscale'), ('rapport', "Rapport d'activité"), ('identite', "Pièce d'identité"), ('registre', 'Registre de commerce'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(upload_to=documents.models.upload_path)),
                ('statut', models.CharField(choices=[('prive', 'Privé'), ('partage', 'Partagé avec expert'), ('archive', 'Archivé')], default='prive', max_length=20)),
                ('taille', models.PositiveIntegerField(default=0, help_text='Taille en octets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_partages', to=settings.AUTH_USER_MODEL)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
