# Generated by Django 6.0.2 on 2026-04-21 21:51

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_expiration',
            field=models.DateField(blank=True, help_text="Date d'expiration du document", null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='experts_partage',
            field=models.ManyToManyField(blank=True, related_name='documents_partages_multi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='mots_cles',
            field=models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=300),
        ),
        migrations.AddField(
            model_name='document',
            name='nb_telechargements',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='numero_reference',
            field=models.CharField(blank=True, help_text='Référence interne ou légale', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('contrat', 'Contrat'), ('facture', 'Facture'), ('declaration', 'Déclaration fiscale'), ('rapport', "Rapport d'activité"), ('identite', "Pièce d'identité"), ('registre', 'Registre de commerce'), ('juridique', 'Document juridique'), ('assurance', 'Assurance'), ('judiciaire', 'Document judiciaire'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='statut',
            field=models.CharField(choices=[('prive', 'Privé'), ('partage', 'Partagé avec expert'), ('en_revision', 'En révision'), ('signe', 'Signé'), ('archive', 'Archivé')], default='prive', max_length=20),
        ),
        migrations.CreateModel(
            name='CommentaireDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('est_expert', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='documents.document')),
            ],
            options={
                'verbose_name': 'Commentaire de document',
                'verbose_name_plural': 'Commentaires de documents',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VersionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=documents.models.version_upload_path)),
                ('taille', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, help_text='Note sur les changements', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
            ],
            options={
                'verbose_name': 'Version de document',
                'verbose_name_plural': 'Versions de documents',
                'ordering': ['-numero'],
            },
        ),
    ]
