# Generated by Django 6.0.2 on 2026-07-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('role_cible', models.CharField(choices=[('commercant', 'Commerçant'), ('prestataire', 'Prestataire de services'), ('expert', 'Expert juridique / comptable'), ('institution', 'Institution / ONG'), ('admin', 'Administrateur')], help_text="Role auquel ce plan s'adresse", max_length=20)),
                ('prix', models.DecimalField(decimal_places=0, help_text='Prix en FCFA', max_digits=10)),
                ('periode_jours', models.PositiveIntegerField(choices=[(30, 'Mensuel'), (365, 'Annuel')], default=30)),
                ('description', models.TextField(blank=True)),
                ('max_contrats_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('max_dossiers_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('max_messages_chatbot_mois', models.PositiveIntegerField(blank=True, null=True)),
                ('mise_en_avant_annuaire', models.BooleanField(default=False, help_text="Reserve aux experts : mise en avant dans l'annuaire")),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['role_cible', 'prix'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente_paiement', 'En attente de paiement'), ('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente_paiement', max_length=25)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.plan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('moyen_paiement', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('carte', 'Carte bancaire')], max_length=20)),
                ('reference_transaction', models.CharField(help_text='Identifiant genere cote Legal Connect', max_length=100, unique=True)),
                ('reference_externe', models.CharField(blank=True, help_text="Identifiant renvoye par l'operateur/CinetPay", max_length=150)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirme_le', models.DateTimeField(blank=True, null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='abonnements.abonnement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
