# Generated by Django 6.0.2 on 2026-07-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone',
            field=models.CharField(blank=True, help_text="Numero Mobile Money a debiter (saisi par l'utilisateur)", max_length=20),
        ),
    ]
