# Generated by Django 6.0.2 on 2026-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_paiement_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_documents_mois',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
