# Generated by Django 6.0.2 on 2026-07-02 16:08

import collaboration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=collaboration.models.upload_dossier, verbose_name='Fichier joint'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
