# Generated by Django 6.0.2 on 2026-03-01 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('nouveau_dossier', 'Nouveau dossier soumis'), ('dossier_valide', 'Dossier validé'), ('dossier_rejete', 'Dossier rejeté'), ('nouveau_message', 'Nouveau message reçu'), ('contrat_genere', 'Contrat généré'), ('echeance_7j', 'Échéance dans 7 jours'), ('echeance_1j', 'Échéance demain'), ('echeance_depassee', 'Échéance dépassée'), ('nouveau_commentaire', 'Nouveau commentaire'), ('document_partage', 'Document partagé')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=300)),
                ('lu', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
